#!/bin/bash

# Set it to an existing directory with write permission for the current user
# This is the location for data persistency
export CEDAR_DOCKER_HOME=~/cedar-docker-deployment

# CEDAR hostname for backend services
export CEDAR_HOST=metadatacenter.orgx

# Docker network, IP address
export CEDAR_NET_GATEWAY=192.168.17.1

# Keycloak admin user and connection data
export CEDAR_KEYCLOAK_ADMIN_USER="administrator"
export CEDAR_KEYCLOAK_ADMIN_PASSWORD="changeme"
export CEDAR_KEYCLOAK_HOST="${CEDAR_NET_GATEWAY}"
export CEDAR_KEYCLOAK_PORT=8080

# cedar-admin user data
# You should change this before the first run
# 64 characters, [0-9, a-f]
export CEDAR_ADMIN_USER_API_KEY="0000111122223333444455556666777788889999aaaabbbbccccddddeeeeffff"
export CEDAR_ADMIN_USER_PASSWORD="changeme"

# Mongo user and connection data
export CEDAR_MONGO_ROOT_USER_NAME="mongoRootUser"
export CEDAR_MONGO_ROOT_USER_PASSWORD="changeme"
export CEDAR_MONGO_APP_USER_NAME="cedarMongoUser"
export CEDAR_MONGO_APP_USER_PASSWORD="changeme"
export CEDAR_MONGO_HOST="${CEDAR_NET_GATEWAY}"
export CEDAR_MONGO_PORT=27017

# MySQL CEDAR app user data for Keycloak persistence
export CEDAR_MYSQL_ROOT_PASSWORD="changeme"
export CEDAR_MYSQL_USER="cedarMySQLUser"
export CEDAR_MYSQL_PASSWORD="changeme"
export CEDAR_MYSQL_HOST="${CEDAR_NET_GATEWAY}"
export CEDAR_MYSQL_PORT=3306

# Neo4j user and connection data - do not change the user name
export CEDAR_NEO4J_USER_PASSWORD="changeme"
export CEDAR_NEO4J_HOST="${CEDAR_NET_GATEWAY}"
export CEDAR_NEO4J_REST_PORT=7474
export CEDAR_NEO4J_BOLT_PORT=7687

# Port assignment
export CEDAR_KIBANA_PORT=5601
export CEDAR_REDIS_COMMANDER_PORT=8081

# Microservices host
export CEDAR_MICROSERVICE_HOST="${CEDAR_NET_GATEWAY}"

# Microservice ports
export CEDAR_FOLDER_HTTP_PORT=9008
export CEDAR_FOLDER_ADMIN_PORT=$((${CEDAR_FOLDER_HTTP_PORT} + 100))
export CEDAR_FOLDER_STOP_PORT=$((${CEDAR_FOLDER_HTTP_PORT} + 200))
export CEDAR_GROUP_HTTP_PORT=9009
export CEDAR_GROUP_ADMIN_PORT=$((${CEDAR_GROUP_HTTP_PORT} + 100))
export CEDAR_GROUP_STOP_PORT=$((${CEDAR_GROUP_HTTP_PORT} + 200))
export CEDAR_REPO_HTTP_PORT=9002
export CEDAR_REPO_ADMIN_PORT=$((${CEDAR_REPO_HTTP_PORT} + 100))
export CEDAR_REPO_STOP_PORT=$((${CEDAR_REPO_HTTP_PORT} + 200))
export CEDAR_RESOURCE_HTTP_PORT=9007
export CEDAR_RESOURCE_ADMIN_PORT=$((${CEDAR_RESOURCE_HTTP_PORT} + 100))
export CEDAR_RESOURCE_STOP_PORT=$((${CEDAR_RESOURCE_HTTP_PORT} + 200))
export CEDAR_SCHEMA_HTTP_PORT=9003
export CEDAR_SCHEMA_ADMIN_PORT=$((${CEDAR_SCHEMA_HTTP_PORT} + 100))
export CEDAR_SCHEMA_STOP_PORT=$((${CEDAR_SCHEMA_HTTP_PORT} + 200))
export CEDAR_SUBMISSION_HTTP_PORT=9010
export CEDAR_SUBMISSION_ADMIN_PORT=$((${CEDAR_SUBMISSION_HTTP_PORT} + 100))
export CEDAR_SUBMISSION_STOP_PORT=$((${CEDAR_SUBMISSION_HTTP_PORT} + 200))
export CEDAR_TEMPLATE_HTTP_PORT=9001
export CEDAR_TEMPLATE_ADMIN_PORT=$((${CEDAR_TEMPLATE_HTTP_PORT} + 100))
export CEDAR_TEMPLATE_STOP_PORT=$((${CEDAR_TEMPLATE_HTTP_PORT} + 200))
export CEDAR_TERMINOLOGY_HTTP_PORT=9004
export CEDAR_TERMINOLOGY_ADMIN_PORT=$((${CEDAR_TERMINOLOGY_HTTP_PORT} + 100))
export CEDAR_TERMINOLOGY_STOP_PORT=$((${CEDAR_TERMINOLOGY_HTTP_PORT} + 200))
export CEDAR_USER_HTTP_PORT=9005
export CEDAR_USER_ADMIN_PORT=$((${CEDAR_USER_HTTP_PORT} + 100))
export CEDAR_USER_STOP_PORT=$((${CEDAR_USER_HTTP_PORT} + 200))
export CEDAR_VALUERECOMMENDER_HTTP_PORT=9006
export CEDAR_VALUERECOMMENDER_ADMIN_PORT=$((${CEDAR_VALUERECOMMENDER_HTTP_PORT} + 100))
export CEDAR_VALUERECOMMENDER_STOP_PORT=$((${CEDAR_VALUERECOMMENDER_HTTP_PORT} + 200))
export CEDAR_WORKER_HTTP_PORT=9011
export CEDAR_WORKER_ADMIN_PORT=$((${CEDAR_WORKER_HTTP_PORT} + 100))
export CEDAR_WORKER_STOP_PORT=$((${CEDAR_WORKER_HTTP_PORT} + 200))

# Frontend
export CEDAR_FRONTEND_HOST="${CEDAR_NET_GATEWAY}"
export CEDAR_FRONTEND_PORT=4200

# Redis
export CEDAR_REDIS_PERSISTENT_HOST="${CEDAR_NET_GATEWAY}"
export CEDAR_REDIS_PERSISTENT_PORT=6379
export CEDAR_REDIS_NONPERSISTENT_HOST="${CEDAR_NET_GATEWAY}"
export CEDAR_REDIS_NONPERSISTENT_PORT=6380

# Bioportal
export CEDAR_BIOPORTAL_REST_BASE="http://data.bioontology.org/"

# Elasticsearch
export CEDAR_ELASTICSEARCH_HOST="${CEDAR_NET_GATEWAY}"
export CEDAR_ELASTICSEARCH_REST_PORT=9200
export CEDAR_ELASTICSEARCH_TRANSPORT_PORT=9300

# Nginx
export CEDAR_NGINX_HTTP_PORT=80
export CEDAR_NGINX_HTTPS_PORT=443

