server {
  listen 80 default_server;
  server_name _;

  location / {
    proxy_pass http://host.docker.internal:4202;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    add_header X-Cedar-Routing-Mode designer always;
  }
}
