services:
  redis-commander:
    container_name: admin-redis-commander
    image: "metadatacenter/cedar-admin-redis-commander:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-admin-redis-commander
    networks:
      - cedarnet
    ports:
      - ${CEDAR_REDIS_COMMANDER_PORT}:8081
    environment:
      - CEDAR_NET_GATEWAY

  kibana:
    container_name: admin-kibana
    image: "metadatacenter/cedar-admin-kibana:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-admin-kibana
    networks:
      - cedarnet
    ports:
      - ${CEDAR_KIBANA_PORT}:5601

  phpmyadmin:
    container_name: admin-phpmyadmin
    image: "metadatacenter/cedar-admin-phpmyadmin:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-admin-phpmyadmin
    networks:
      - cedarnet
    ports:
      - ${CEDAR_PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1

  admin-tool:
    container_name: admin-tool
    image: "metadatacenter/cedar-admin-tool:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-admin-tool
    networks:
      - cedarnet
    volumes:
      - cedar_ca:/cedar/ca
    environment:
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_MONGO_HOST
      - CEDAR_MONGO_PORT
      - CEDAR_ADMIN_USER_PASSWORD
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_NEO4J_HOST
      - CEDAR_NEO4J_REST_PORT
      - CEDAR_NEO4J_BOLT_PORT
      - CEDAR_NEO4J_USER_NAME
      - CEDAR_NEO4J_USER_PASSWORD
      - CEDAR_SALT_API_KEY
      - CEDAR_CADSR_ADMIN_USER_API_KEY
      - CEDAR_REDIS_PERSISTENT_HOST
      - CEDAR_REDIS_PERSISTENT_PORT
      - CEDAR_RESOURCE_SERVER_HOST
    extra_hosts:
      - "auth.${CEDAR_HOST}:${CEDAR_NGINX_HOST}"


networks:
  cedarnet:
    name: cedarnet
    external: true

volumes:
  cedar_ca:
    name: cedar_ca
    external: true
